name: 'Tag PRs in a workflow'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  workflow-run-id:
    type: string
    description: The workflow run ID to start the search for workflows from. Defaults to the current workflow run.
    required: false
    default: ${{ github.run_id }}
  access-token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: ${{ github.token }}
    required: false
  tag:
    type: string
    required: true
    description: 'tag the PRs with this tag'
    default: 'deployed'
  paths:
    description: |-
      comma list of paths to check for when filtering the commits
    required: false
  dry-run:
    type: boolean
    description: |-
      if true, will not actually tag the PRs, just print the ones that would be tagged
    required: false
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
